export const Users = [
    {
      id:1,
      profilePicture: "assets/people/1.jpeg",
      username: "John Roy",
    },
    {
      id:2,
      profilePicture: "assets/people/2.png",
      username: "Celina Wood",
    },
    {
      id:3,
      profilePicture: "assets/people/3.jpeg",
      username: "Jenni Roy",
    },
    {
      id:4,
      profilePicture: "assets/people/4.png",
      username: "Rick Richford",
    },
    {
      id:5,
      profilePicture: "assets/people/5.png",
      username: "Alex Dunphy",
    },                                                      
    {
      id:6,
      profilePicture: "assets/people/6.jpeg",
      username: "Phil Prichett",
    },
    {
      id:7,
      profilePicture: "assets/people/7.png",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/people/8.jpeg",
      username: "Haley Thomas",
    },
    {
      id:9,
      profilePicture: "assets/people/9.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/people/10.png",
      username: "Sofia Williams",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "It's so delicious",
      photo: "assets/posts/post1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 40,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/post2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/posts/post3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/post5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/post6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];